<?php

namespace KingdomGameBundle\Repository;

/**
 * BattleUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleUnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
