<?php

namespace KingdomGameBundle\Repository;

/**
 * BuildingCostResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingCostResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
