<?php

namespace KingdomGameBundle\Repository;

/**
 * BuildingCostTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingCostTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
