<?php

namespace KingdomGameBundle\Repository;

/**
 * BuildingsProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingsProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
