<?php

namespace KingdomGameBundle\Repository;

/**
 * GameResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
