<?php

namespace KingdomGameBundle\Repository;

/**
 * KingdomBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingdomBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
