<?php

namespace KingdomGameBundle\Repository;

/**
 * KingdomUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingdomUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
