<?php

namespace KingdomGameBundle\Repository;

/**
 * UnitCostTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitCostTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
