<?php

namespace KingdomGameBundle\Repository;

/**
 * UnitBuildingDependencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitBuildingDependencyRepository extends \Doctrine\ORM\EntityRepository
{
}
