<?php

namespace KingdomGameBundle\Repository;

/**
 * UnitCostResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitCostResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
