<?php

namespace KingdomGameBundle\Repository;

/**
 * UnitProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
