<?php

namespace KingdomGameBundle\Repository;

/**
 * UnitCoefficientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitCoefficientRepository extends \Doctrine\ORM\EntityRepository
{
}
