<?php

namespace Proxies\__CG__\KingdomGameBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Kingdom extends \KingdomGameBundle\Entity\Kingdom implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'id', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'name', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'x', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'y', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'player', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'resources', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'buildings', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'units'];
        }

        return ['__isInitialized__', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'id', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'name', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'x', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'y', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'player', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'resources', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'buildings', '' . "\0" . 'KingdomGameBundle\\Entity\\Kingdom' . "\0" . 'units'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Kingdom $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setX($x)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX', [$x]);

        return parent::setX($x);
    }

    /**
     * {@inheritDoc}
     */
    public function getX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX', []);

        return parent::getX();
    }

    /**
     * {@inheritDoc}
     */
    public function setY($y)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setY', [$y]);

        return parent::setY($y);
    }

    /**
     * {@inheritDoc}
     */
    public function getY()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getY', []);

        return parent::getY();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlayer', []);

        return parent::getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlayer(\KingdomGameBundle\Entity\Player $player)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlayer', [$player]);

        return parent::setPlayer($player);
    }

    /**
     * {@inheritDoc}
     */
    public function getResources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResources', []);

        return parent::getResources();
    }

    /**
     * {@inheritDoc}
     */
    public function setResources(array $resources)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResources', [$resources]);

        return parent::setResources($resources);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildings', []);

        return parent::getBuildings();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildings(array $buildings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildings', [$buildings]);

        return parent::setBuildings($buildings);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnits', []);

        return parent::getUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnits(array $units)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnits', [$units]);

        return parent::setUnits($units);
    }

}
